# Generated by Django 3.1.5 on 2022-04-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20220427_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
