# Generated by Django 3.1.5 on 2022-04-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_auto_20220427_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
    ]
