# Generated by Django 3.1.5 on 2022-04-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_remove_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.FloatField(default=1),
        ),
    ]
